### PR TITLE
Resolve issue #10 and #27

### PR DESCRIPTION
**Pull request by cwhwang1986**

### CODE REVIEW

**Comment by JustinWebb** [comment]
What window are you using it on?  If it's inside Angular, you should inject and use `$window` instead.

Also, this commit is marked like so:
```
We can’t automatically merge this pull request.
Use the command line to resolve conflicts before continuing.
```

I just handled Katrina and Austin's pull requests.  I suggest you accept my pull request, rebase from upstream locally, then submit a new pull request after you've incorporated my conflict fixes.

**Comment by cwhwang1986** [comment]
Okay, I will rebase my repo once you submit the pull request.

**Comment by JustinWebb** [comment]
My pull request is already there.

**Comment by JustinWebb** [comment]
My bad - my pull request wasn't there before.  It's there now.

**Comment by JustinWebb** [comment]
Good work, Charlie.  Thanks.

**Pull request merged**
